### ISSUE TITLE
Root write

### ISSUE THREAD

**Issue by giper45** [Apkawa/ansible-role-nfs#1]
Hello,
I need to allow root nfs clients to write files on shared folder, with root permission. 
Actually nfs clients write file with nfsnobody user. 
Can you suggest anything ? 
Thanks in advance.

**Comment by giper45** [comment]
Hi, I have solved in the followed way: 
``` 
nfs_server: yes
nfs_client: no

nfs_server_shares:
    - path: "{{ nfs_docker_volume_path }}"
      allow:
        - ip: "*"
          options:
          - rw
          - sync
          - no_root_squash
```   
Thanks anyway!
